### PR TITLE
Fix build for Coq v8.10.1

### PR DESCRIPTION
**Pull request by k4rtik**

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
I would typically recommend putting unrelated changes in separate commits, but that's not a big deal.

**Comment by Zimmi48** [comment]
@k4rtik Thanks for your interest in updating this project and the "semantics" contrib. If these projects are of interest to you, maybe you would consider becoming their maintainer in the context of coq-community? We regularly transfer former contribs to coq-community when we can find a volunteer to be their official maintainer. The ideas being coq-community are described in the following repository, which is also where the projects to move are being discussed: https://github.com/coq-community/manifesto

**Comment by k4rtik** [comment]
Hi @Zimmi48 

> If these projects are of interest to you, maybe you would consider becoming their maintainer in the context of coq-community?

Sure! I'd love to. I read the manifesto and it seems like I may not be as unqualified as I initially thought after reading your comment.

**Comment by Zimmi48** [comment]
Cool! Then, can I let you open issues in the manifesto repo for one or both of these projects?

**Pull request merged**
